_loadout = switch (toLower (typeOf _this)) do 
{
	case "uk3cb_baf_sc_arctic_rec": {[["UK3CB_BAF_L119A1_SpecterLDS_UKUGL","UK3CB_BAF_Silencer_L85","UK3CB_BAF_LLM_IR_Black","rhsusf_acc_ACOG_RMR",["UK3CB_BAF_556_30Rnd_T",30],["UK3CB_BAF_1Rnd_HEDP_Grenade_Shell",1],""],[],["UK3CB_BAF_L131A1","","","",["UK3CB_BAF_9_17Rnd",17],[],""],["UK3CB_BAF_U_Smock_Arctic",[["ACE_bloodIV_500",1],["ACE_fieldDressing",10],["ACRE_PRC148",1],["ACRE_PRC343",1],["ACE_EarPlugs",1],["ACE_epinephrine",1],["ACE_tourniquet",1],["ACE_Flashlight_XL50",1]]],["UK3CB_BAF_V_PLCE_Webbing_Plate_Winter",[["UK3CB_BAF_556_30Rnd_T",10,30],["UK3CB_BAF_1Rnd_HEDP_Grenade_Shell",12,1],["UK3CB_BAF_1Rnd_SmokeOrange_Grenade_shell",2,1],["UK3CB_BAF_1Rnd_SmokeBlue_Grenade_shell",2,1]]],["UK3CB_BAF_B_Bergen_Arctic_SL_A",[["UK3CB_BAF_LLM_Flashlight_Black",1],["rhs_mag_m67",3,1],["UK3CB_BAF_556_30Rnd_T",5,30],["UK3CB_BAF_1Rnd_HE_Grenade_Shell",6,1]]],"UK3CB_BAF_H_Mk7_Win_A","",["Rangefinder","","","",[],[],""],["ItemMap","ItemGPS","","ItemCompass","ACE_Altimeter",""]]};
	case "uk3cb_baf_explosive_arctic_rec": {[["UK3CB_BAF_L119A1_SpecterLDS_FG","UK3CB_BAF_Silencer_L85","UK3CB_BAF_LLM_IR_Black","rhsusf_acc_ACOG_RMR",["UK3CB_BAF_556_30Rnd",30],[],"UK3CB_underbarrel_acc_grippod"],["UK3CB_BAF_NLAW_Launcher","","","",[],[],""],["UK3CB_BAF_L131A1","","","",["UK3CB_BAF_9_17Rnd",17],[],""],["UK3CB_BAF_U_Smock_Arctic",[["ACRE_PRC343",1],["ACE_fieldDressing",10],["ACE_bloodIV_500",1],["ACE_EarPlugs",1],["ACE_tourniquet",1],["ACE_EntrenchingTool",1]]],["UK3CB_BAF_V_PLCE_Webbing_Plate_Winter",[["UK3CB_BAF_556_30Rnd_T",10,30],["rhs_mag_m67",4,1],["UK3CB_BAF_9_17Rnd",2,17]]],["UK3CB_BAF_B_Carryall_Arctic",[["ACE_Clacker",1],["ACE_Flashlight_XL50",1],["UK3CB_BAF_LLM_Flashlight_Black",1],["UK3CB_BAF_556_30Rnd_T",5,30],["UK3CB_BAF_SmokeShellBlue",2,1],["UK3CB_BAF_SmokeShellOrange",2,1],["rhsusf_m112_mag",4,1],["ATMine_Range_Mag",1,1]]],"UK3CB_BAF_H_Mk7_Win_A","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","","ItemCompass","ACE_Altimeter",""]]};
	case "uk3cb_baf_medic_arctic_rec": {[["UK3CB_BAF_L119A1_SpecterLDS_FG","UK3CB_BAF_Silencer_L85","UK3CB_BAF_LLM_IR_Black","rhsusf_acc_ACOG_RMR",["UK3CB_BAF_556_30Rnd",30],[],"UK3CB_underbarrel_acc_grippod"],[],["UK3CB_BAF_L131A1","","","",["UK3CB_BAF_9_17Rnd",17],[],""],["UK3CB_BAF_U_Smock_Arctic",[["ACRE_PRC343",1],["ACE_fieldDressing",10],["ACE_EarPlugs",1],["ACE_bloodIV_500",1],["ACE_tourniquet",1],["ACE_morphine",1],["ACE_epinephrine",1]]],["UK3CB_BAF_V_PLCE_Webbing_Plate_Winter",[["UK3CB_BAF_556_30Rnd_T",12,30],["UK3CB_BAF_9_17Rnd",2,17],["rhs_mag_m67",2,1],["SmokeShellYellow",6,1]]],["UK3CB_BAF_B_Bergen_Arctic_Rifleman_B",[["ACE_fieldDressing",30],["ACE_bloodIV",4],["ACE_bloodIV_250",8],["ACE_bloodIV_500",6],["ACE_EntrenchingTool",1],["ACE_epinephrine",10],["ACE_morphine",12],["ACE_tourniquet",5],["ACE_Flashlight_XL50",1],["UK3CB_BAF_LLM_Flashlight_Black",1]]],"UK3CB_BAF_H_Mk7_Win_A","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","","ItemCompass","ACE_Altimeter",""]]};
	case "uk3cb_baf_mglmg_arctic_rec": {[["UK3CB_BAF_L110A2_RIS_LDSR2D_IR_S","UK3CB_BAF_Silencer_L110","UK3CB_BAF_LLM_IR_Black","rhsusf_acc_ACOG_RMR",["UK3CB_BAF_556_200Rnd_T",200],[],""],[],["UK3CB_BAF_L131A1","","","",["UK3CB_BAF_9_17Rnd",17],[],""],["UK3CB_BAF_U_Smock_Arctic",[["ACRE_PRC343",1],["ACE_bloodIV_500",1],["ACE_EarPlugs",1],["ACE_EntrenchingTool",1],["ACE_epinephrine",1],["ACE_fieldDressing",10],["ACE_tourniquet",1]]],["UK3CB_BAF_V_PLCE_Webbing_Plate_Winter",[["UK3CB_BAF_9_17Rnd",2,17],["UK3CB_BAF_SmokeShellOrange",2,1],["UK3CB_BAF_SmokeShellBlue",2,1],["rhs_mag_m67",5,1],["UK3CB_BAF_556_200Rnd_T",2,200]]],["UK3CB_BAF_B_Carryall_Arctic",[["ACE_Flashlight_XL50",1],["UK3CB_BAF_LLM_Flashlight_Black",1],["UK3CB_BAF_556_200Rnd_T",4,200]]],"UK3CB_BAF_H_Mk7_Win_A","",["Rangefinder","","","",[],[],""],["ItemMap","ItemGPS","","ItemCompass","ACE_Altimeter",""]]};
	case "uk3cb_baf_pointman_arctic_rec": {[["UK3CB_BAF_L119A1_SpecterLDS_FG","UK3CB_BAF_Silencer_L85","UK3CB_BAF_LLM_IR_Black","rhsusf_acc_ACOG_RMR",["UK3CB_BAF_556_30Rnd",30],[],"UK3CB_underbarrel_acc_grippod"],[],["UK3CB_BAF_L131A1","","","",["UK3CB_BAF_9_17Rnd",17],[],""],["UK3CB_BAF_U_Smock_Arctic",[["ACE_EarPlugs",1],["ACE_fieldDressing",10],["ACRE_PRC148",1],["ACRE_PRC343",1],["ACE_epinephrine",1],["ACE_bloodIV_500",1],["ACE_morphine",2],["ACE_tourniquet",1]]],["UK3CB_BAF_V_PLCE_Webbing_Plate_Winter",[["UK3CB_BAF_556_30Rnd_T",10,30],["UK3CB_BAF_9_17Rnd",2,17],["B_IR_Grenade",1,1],["UK3CB_BAF_SmokeShellOrange",2,1],["UK3CB_BAF_SmokeShellBlue",2,1],["rhs_mag_m67",3,1]]],["UK3CB_BAF_B_Carryall_Arctic",[["ACE_EntrenchingTool",1],["ACE_rangeCard",1],["ACE_Clacker",1],["ACE_MapTools",1],["ACE_Flashlight_XL50",1],["ACE_SpottingScope",1],["ACE_Kestrel4500",1],["ACE_DAGR",1],["UK3CB_BAF_LLM_Flashlight_Black",1],["ClaymoreDirectionalMine_Remote_Mag",2,1]]],"UK3CB_BAF_H_Mk7_Win_A","",["Rangefinder","","","",[],[],""],["ItemMap","ItemGPS","","ItemCompass","ACE_Altimeter",""]]};
	case "uk3cb_baf_marksman_arctic_rec": {[["UK3CB_BAF_L129A1_RKSL_PMII_312_sunshade_IR","UK3CB_BAF_Silencer_L115A3","UK3CB_BAF_LLM_IR_Black","RKSL_optic_PMII_312_sunshade",["UK3CB_BAF_762_L42A1_20Rnd",20],[],"UK3CB_underbarrel_acc_fgrip_bipod"],[],["UK3CB_BAF_L131A1","","","",["UK3CB_BAF_9_17Rnd",17],[],""],["UK3CB_BAF_U_Smock_Arctic",[["ACE_EarPlugs",1],["ACRE_PRC343",1],["ACE_fieldDressing",10],["ACE_bloodIV_500",1],["ACE_morphine",2],["ACE_tourniquet",1]]],["UK3CB_BAF_V_PLCE_Webbing_Plate_Winter",[["UK3CB_BAF_762_L42A1_20Rnd",3,20],["UK3CB_BAF_762_L42A1_20Rnd_T",3,20],["UK3CB_BAF_9_17Rnd",2,17]]],["UK3CB_BAF_B_Carryall_Arctic",[["ACE_EntrenchingTool",1],["ACE_DAGR",1],["ACE_Kestrel4500",1],["ACE_rangeCard",1],["ACE_Flashlight_XL50",1],["UK3CB_BAF_LLM_Flashlight_Black",1],["UK3CB_BAF_SmokeShellOrange",2,1],["UK3CB_BAF_SmokeShellBlue",2,1],["HandGrenade",3,1]]],"UK3CB_BAF_H_Mk7_Win_A","UK3CB_BAF_G_Tactical_Clear",["Rangefinder","","","",[],[],""],["ItemMap","ItemGPS","","ItemCompass","ACE_Altimeter",""]]};
	case "uk3cb_baf_fac_arctic_rec": {[["UK3CB_BAF_L119A1_SpecterLDS_UKUGL","UK3CB_BAF_Silencer_L85","UK3CB_BAF_LLM_IR_Black","rhsusf_acc_ACOG_RMR",["UK3CB_BAF_556_30Rnd_T",30],["UK3CB_BAF_1Rnd_SmokePurple_Grenade_shell",1],""],[],["UK3CB_BAF_L131A1","","","",["UK3CB_BAF_9_17Rnd",17],[],""],["UK3CB_BAF_U_Smock_Arctic",[["ACRE_PRC343",1],["ACRE_PRC148",1],["ACE_fieldDressing",10],["ACE_bloodIV_500",1],["ACE_EarPlugs",1],["ACE_epinephrine",1],["ACE_morphine",1],["ACE_tourniquet",1],["ACE_MapTools",1]]],["UK3CB_BAF_V_PLCE_Webbing_Plate_Winter",[["UK3CB_BAF_556_30Rnd_T",10,30],["UK3CB_BAF_1Rnd_SmokePurple_Grenade_shell",6,1],["UK3CB_BAF_UGL_FlareRed_F",4,1],["UK3CB_BAF_UGL_FlareGreen_F",4,1]]],["UK3CB_BAF_B_Bergen_Arctic_JTAC_A",[["ACE_Flashlight_XL50",1],["UK3CB_BAF_LLM_IR_Black",1],["B_IR_Grenade",2,1],["UK3CB_BAF_SmokeShellPurple",4,1],["rhs_mag_m67",2,1],["UK3CB_BAF_1Rnd_HEDP_Grenade_Shell",6,1]]],"UK3CB_BAF_H_Mk7_Win_A","G_Tactical_Clear",["UK3CB_BAF_Soflam_Laserdesignator","","","",[],[],""],["ItemMap","ItemGPS","","ItemCompass","ACE_Altimeter",""]]};
};

removeUniform player;
removeAllWeapons player;
removeAllItems player;
removeAllAssignedItems player;
removebackpack player;
removeVest player;
removeHeadGear player;

_this setUnitLoadout _loadout;
